name: Build and test main
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      
permissions:
  checks: write
  
jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: Audit dependencies
        uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Test and build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Rust dependencies
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run tests
        run: cargo test --release -- --nocapture
      - name: Run Benchmark performance test
        run: cargo bench --bench performance
      - name: Run Criterion benchmark
        run: cargo bench --bench criterion_bench
      - name: Build
        run: cargo build --release
  
