name: Publish main
on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push multi-platform image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pdfgen
          tag: ${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64
